services:
  kitten_expo:
    container_name: kitten_api

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - expo_network
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGUSER: "postgres"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - expo_network





networks:
  expo_network:
    name: expo_network
volumes:
  postgres_data: