# Generated by Django 5.1.1 on 2024-10-02 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
