# Generated by Django 5.1.1 on 2024-10-04 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten_api', '0003_alter_kitten_owner_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='color',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')]),
        ),
    ]
